default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: Ali12345
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: recipe-rails-100_development
  user: postgres
  password: Ali12345

test:
  <<: *default
  database: recipe-rails-100_test
  user: postgres
  password: Ali12345

production:
  <<: *default
  database: recipe-rails_production
  username: blog-app
  password: <%= ENV["HELLORAILS_DATABASE_PASSWORD"] %>
